### ISSUE TITLE
Make tip() method return tip_id

### ISSUE THREAD

**Issue by mradkov** [aeternity/tipping-contract#4]
Can we make the tip() method return the `tip_id` of the newly created tip? 

This way we will be able to easily redirect the user from the wallet activity history to the correct corresponding tip preview page for the transaction.

https://github.com/aeternity/tipping-contract/blob/35deec81b5f8632802e8d4c207fe25753e14a1c9/contracts/Tipping.aes#L82

**Comment by thepiwo** [comment]
already implemented
